### ISSUE TITLE
Dashcast namespace issue in HA 2023.4.5 / supervisor 10.0

### ISSUE THREAD

**Issue by pvmil** [AlexxIT/DashCast#13]
Today I've updated to HA 2023.4.5 / supervisor 10.0.

My service calls to DashCast stopped working, with errors like the one below in the HA logging.
It complains: Namespace urn:x-cast:com.madmod.dashcast is not supported by current app. 
This when executing a DashCast:DashCast service call which was working fine before (I was a really happy user :)

Logging:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/dash_cast/__init__.py:25
Integration: DashCast ([documentation](https://github.com/AlexxIT/DashCast), [issues](https://github.com/AlexxIT/DashCast/issues))
First occurred: 17:29:17 (1 occurrences)
Last logged: 17:29:17

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Namespace urn:x-cast:com.madmod.dashcast is not supported by current app. Supported are urn:x-cast:com.google.cast.cac, urn:x-cast:com.google.cast.debugoverlay, urn:x-cast:com.google.cast.broadcast, urn:x-cast:com.google.cast.media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 452, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/dash_cast/__init__.py", line 25, in play_media
    dash.load_url(url, force)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/dashcast.py", line 55, in load_url
    self.launch(callback_function=launch_callback)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/__init__.py", line 60, in launch
    self._socket_client.receiver_controller.launch_app(
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/receiver.py", line 147, in launch_app
    self._send_launch_message(app_id, force_launch, callback_function)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/receiver.py", line 169, in _send_launch_message
    callback_function()
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/dashcast.py", line 51, in launch_callback
    self.send_message(
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/__init__.py", line 107, in send_message
    self.launch(
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/__init__.py", line 60, in launch
    self._socket_client.receiver_controller.launch_app(
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/receiver.py", line 147, in launch_app
    self._send_launch_message(app_id, force_launch, callback_function)
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/receiver.py", line 169, in _send_launch_message
    callback_function()
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/__init__.py", line 108, in <lambda>
    callback_function=lambda: self.send_message_nocheck(
  File "/usr/local/lib/python3.10/site-packages/pychromecast/controllers/__init__.py", line 133, in send_message_nocheck
    self._message_func(
  File "/usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py", line 958, in send_app_message
    raise UnsupportedNamespace(
pychromecast.error.UnsupportedNamespace: Namespace urn:x-cast:com.madmod.dashcast is not supported by current app. Supported are urn:x-cast:com.google.cast.cac, urn:x-cast:com.google.cast.debugoverlay, urn:x-cast:com.google.cast.broadcast, urn:x-cast:com.google.cast.medi
```

**Comment by FlexxFR** [comment]
Any updates or solutions on this?
I just install this integration for the first time but I got the same errors

**Comment by AlexxIT** [comment]
Is the problem still relevant?

**Comment by FlexxFR** [comment]
old one :)
Can't remember exactly the details anymore but I just checked my logs and don't notice any issues with DashCast. Still using it to continuously cast dashboards to 5 Nest Hubs, no issues to report from my side.
