### ISSUE TITLE
Won’t work is Sonos integration is active

### ISSUE THREAD

**Issue by ikolsteren** [AlexxIT/DashCast#9]
For some reason when I try and cast it displays an error:
Cast to Displays: Error Executing Script.  Unexpected error for call_service at pos1:’SonosMediaPlayerEntity’ object has no attribute ‘_chromecast’

The automation is not referencing anything to do with Sonos and not sure its conflicting

**Comment by ikolsteren** [comment]
Interesting it seems to be a problem / conflict with Sonos
When I disable my Sonos Integration it works
Here is the error with Sonos on now
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/dash_cast/__init__.py", line 24, in play_media
    entity._chromecast.register_handler(dash)
AttributeError: 'SonosMediaPlayerEntity' object has no attribute '_chromecast'

**Comment by ikolsteren** [comment]
When I re enabled the Sonos things seem to be working....

**Comment by AlexxIT** [comment]
You shouldn't use Sonos entity_id when calling this service
